#ifndef __EZ_HMI_H
#define __EZ_HMI_H

#include "ez_dolorone.h"

/*颜色*/
#define COLOR_WHITE 0xFFFFFF
#define COLOR_BLACK 0x332C2B

/*字体选择*/
#define FRONT_GLOBAL    TNEB_SIZE_48
#define FRONT_INFO      SONG_SIZE_16

/*页面索引编号*/
#define PAGE_MAIN 1 //主界面
#define PAGE_INFO 2 //信息界面
#define PAGE_CONFIG 3 //设置界面

/***************UI坐标定位****************/
/*界面模板编号*/
#define DEMO_NUMBER 3
#define DEMO_MAIN_1 0
#define DEMO_MAIN_2 1
#define DEMO_MAIN_3 2
/*界面1坐标宏*/
#define PIC_FACE1_MT_WIDTH  470
#define PIC_FACE1_MT_HEIGTH  80

#define PIC_FACE1_MT_IMPULSES_START_X  200
#define PIC_FACE1_MT_IMPULSES_START_Y  50
#define PIC_FACE1_MT_IMPULSES_END_X     (PIC_FACE1_MT_IMPULSES_START_X +  PIC_FACE1_MT_WIDTH)
#define PIC_FACE1_MT_IMPULSES_END_Y     (PIC_FACE1_MT_IMPULSES_START_Y +  PIC_FACE1_MT_HEIGTH)
#define PIC_FACE1_MT_IMPULSES_MID_Y     (PIC_FACE1_MT_IMPULSES_START_Y + PIC_FACE1_MT_HEIGTH/2)
#define PIC_FACE1_MT_INTENSITY_START_X  PIC_FACE1_MT_IMPULSES_START_X
#define PIC_FACE1_MT_INTENSITY_START_Y  PIC_FACE1_MT_IMPULSES_START_Y + 150
#define PIC_FACE1_MT_INTENSITY_END_X     (PIC_FACE1_MT_INTENSITY_START_X +  PIC_FACE1_MT_WIDTH)
#define PIC_FACE1_MT_INTENSITY_END_Y     (PIC_FACE1_MT_INTENSITY_START_Y +  PIC_FACE1_MT_HEIGTH)
#define PIC_FACE1_MT_INTENSITY_MID_Y     (PIC_FACE1_MT_INTENSITY_START_Y + PIC_FACE1_MT_HEIGTH/2)
#define PIC_FACE1_MT_FREQUENCY_START_X  PIC_FACE1_MT_IMPULSES_START_X
#define PIC_FACE1_MT_FREQUENCY_START_Y  PIC_FACE1_MT_INTENSITY_START_Y + 150
#define PIC_FACE1_MT_FREQUENCY_END_X     (PIC_FACE1_MT_FREQUENCY_START_X +  PIC_FACE1_MT_WIDTH)
#define PIC_FACE1_MT_FREQUENCY_END_Y     (PIC_FACE1_MT_FREQUENCY_START_Y +  PIC_FACE1_MT_HEIGTH)
#define PIC_FACE1_MT_FREQUENCY_MID_Y     (PIC_FACE1_MT_FREQUENCY_START_Y + PIC_FACE1_MT_HEIGTH/2)

#define PIC_FACE1_DP_IMPULSES_NUM_START_X  95
#define PIC_FACE1_DP_IMPULSES_NUM_START_Y  PIC_FACE1_MT_IMPULSES_START_Y
#define PIC_FACE1_DP_INTENSITY_NUM_START_X  PIC_FACE1_MT_IMPULSES_NUM_START_X
#define PIC_FACE1_DP_INTENSITY_NUM_START_Y  PIC_FACE1_MT_INTENSITY_START_Y
#define PIC_FACE1_DP_FREQUENCY_NUM_START_X  PIC_FACE1_MT_IMPULSES_NUM_START_X
#define PIC_FACE1_DP_FREQUENCY_NUM_START_Y  PIC_FACE1_MT_FREQUENCY_START_Y

#define PIC_FACE1_MT_STEP_Y 150

/*界面2坐标宏*/
#define PIC_FACE2_MT_WIDTH  400
#define PIC_FACE2_MT_HEIGTH  60

#define PIC_FACE2_MT_IMPULSES_START_X  285
#define PIC_FACE2_MT_IMPULSES_START_Y  45
#define PIC_FACE2_MT_IMPULSES_END_X     (PIC_FACE2_MT_IMPULSES_START_X +  PIC_FACE2_MT_WIDTH)
#define PIC_FACE2_MT_IMPULSES_END_Y     (PIC_FACE2_MT_IMPULSES_START_Y +  PIC_FACE2_MT_HEIGTH)
#define PIC_FACE2_MT_IMPULSES_MID_Y     (PIC_FACE2_MT_IMPULSES_START_Y + PIC_FACE2_MT_HEIGTH/2)
#define PIC_FACE2_MT_INTENSITY_START_X  PIC_FACE2_MT_IMPULSES_START_X
#define PIC_FACE2_MT_INTENSITY_START_Y  PIC_FACE2_MT_IMPULSES_START_Y + 165
#define PIC_FACE2_MT_INTENSITY_END_X     (PIC_FACE2_MT_INTENSITY_START_X +  PIC_FACE2_MT_WIDTH)
#define PIC_FACE2_MT_INTENSITY_END_Y     (PIC_FACE2_MT_INTENSITY_START_Y +  PIC_FACE2_MT_HEIGTH)
#define PIC_FACE2_MT_INTENSITY_MID_Y     (PIC_FACE2_MT_INTENSITY_START_Y + PIC_FACE2_MT_HEIGTH/2)
#define PIC_FACE2_MT_FREQUENCY_START_X  PIC_FACE2_MT_IMPULSES_START_X
#define PIC_FACE2_MT_FREQUENCY_START_Y  PIC_FACE2_MT_INTENSITY_START_Y + 165
#define PIC_FACE2_MT_FREQUENCY_END_X     (PIC_FACE2_MT_FREQUENCY_START_X +  PIC_FACE2_MT_WIDTH)
#define PIC_FACE2_MT_FREQUENCY_END_Y     (PIC_FACE2_MT_FREQUENCY_START_Y +  PIC_FACE2_MT_HEIGTH)
#define PIC_FACE2_MT_FREQUENCY_MID_Y     (PIC_FACE2_MT_FREQUENCY_START_Y + PIC_FACE2_MT_HEIGTH/2)

#define PIC_FACE2_DP_IMPULSES_NUM_START_X  105
#define PIC_FACE2_DP_IMPULSES_NUM_START_Y  40
#define PIC_FACE2_DP_INTENSITY_NUM_START_X  PIC_FACE2_MT_IMPULSES_NUM_START_X
#define PIC_FACE2_DP_INTENSITY_NUM_START_Y  205
#define PIC_FACE2_DP_FREQUENCY_NUM_START_X  PIC_FACE2_MT_IMPULSES_NUM_START_X
#define PIC_FACE2_DP_FREQUENCY_NUM_START_Y  370

#define PIC_FACE2_MT_STEP_Y  160

#define PIC_FACE2_MT_CURSOR_W     10
#define PIC_FACE2_MT_CURSOR_H     30

/*界面3坐标宏*/
#define PIC_FACE3_MT_WIDTH  550
#define PIC_FACE3_MT_HEIGTH  90

#define PIC_FACE3_MT_IMPULSES_START_X  150
#define PIC_FACE3_MT_IMPULSES_START_Y  60
#define PIC_FACE3_MT_IMPULSES_END_X     (PIC_FACE3_MT_IMPULSES_START_X +  PIC_FACE3_MT_WIDTH)
#define PIC_FACE3_MT_IMPULSES_END_Y     (PIC_FACE3_MT_IMPULSES_START_Y +  PIC_FACE3_MT_HEIGTH)
#define PIC_FACE3_MT_IMPULSES_MID_Y     (PIC_FACE3_MT_IMPULSES_START_Y + PIC_FACE3_MT_HEIGTH/2)
#define PIC_FACE3_MT_INTENSITY_START_X  PIC_FACE3_MT_IMPULSES_START_X
#define PIC_FACE3_MT_INTENSITY_START_Y  PIC_FACE3_MT_IMPULSES_START_Y + 150
#define PIC_FACE3_MT_INTENSITY_END_X     (PIC_FACE3_MT_INTENSITY_START_X +  PIC_FACE3_MT_WIDTH)
#define PIC_FACE3_MT_INTENSITY_END_Y     (PIC_FACE3_MT_INTENSITY_START_Y +  PIC_FACE3_MT_HEIGTH)
#define PIC_FACE3_MT_INTENSITY_MID_Y     (PIC_FACE3_MT_INTENSITY_START_Y + PIC_FACE3_MT_HEIGTH/2)
#define PIC_FACE3_MT_FREQUENCY_START_X  PIC_FACE3_MT_IMPULSES_START_X
#define PIC_FACE3_MT_FREQUENCY_START_Y  PIC_FACE3_MT_INTENSITY_START_Y + 150
#define PIC_FACE3_MT_FREQUENCY_END_X     (PIC_FACE3_MT_FREQUENCY_START_X +  PIC_FACE3_MT_WIDTH)
#define PIC_FACE3_MT_FREQUENCY_END_Y     (PIC_FACE3_MT_FREQUENCY_START_Y +  PIC_FACE3_MT_HEIGTH)
#define PIC_FACE3_MT_FREQUENCY_MID_Y     (PIC_FACE3_MT_FREQUENCY_START_Y + PIC_FACE3_MT_HEIGTH/2)

#define PIC_FACE3_MT_STEP_X  90
#define PIC_FACE3_MT_STEP_Y  150

#define PIC_FACE3_MT_CURSOR_W     10
#define PIC_FACE3_MT_CURSOR_H     8

/*信息界面贴图*/
#define PIC_INFO_STRING_ROWINDENT 8    //行缩进
#define PIC_INFO_STRING_LINEINDENT 8    //列缩进
#define PIC_INFO_STRING_ROWSPACING (FRONT_INFO/8*10) //行间隔
#define PIC_INFO_STRING_LINESPACING (FRONT_INFO/8*10) //列间隔

/******************图标贴图*********************/
/*按键目标坐标宏*/

#define PIC_BUTTON_TARGET_INFO_START_X 700
#define PIC_BUTTON_TARGET_INFO_START_Y 30
#define PIC_BUTTON_TARGET_INFO_END_X    (PIC_BUTTON_TARGET_INFO_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_TARGET_INFO_END_Y    (PIC_BUTTON_TARGET_INFO_START_Y + PIC_BUTTON_HEIGTH)

#define PIC_BUTTON_TARGET_CONFIG_START_X 700
#define PIC_BUTTON_TARGET_CONFIG_START_Y 130
#define PIC_BUTTON_TARGET_CONFIG_END_X  (PIC_BUTTON_TARGET_CONFIG_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_TARGET_CONFIG_END_Y  (PIC_BUTTON_TARGET_CONFIG_START_Y + PIC_BUTTON_HEIGTH)

#define PIC_BUTTON_TARGET_POWER_START_X 700
#define PIC_BUTTON_TARGET_POWER_START_Y 380
#define PIC_BUTTON_TARGET_POWER_END_X   (PIC_BUTTON_TARGET_POWER_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_TARGET_POWER_END_Y   (PIC_BUTTON_TARGET_POWER_START_Y + PIC_BUTTON_HEIGTH)

#define PIC_BUTTON_TARGET_BACK_START_X 700
#define PIC_BUTTON_TARGET_BACK_START_Y 380
#define PIC_BUTTON_TARGET_BACK_END_X   (PIC_BUTTON_TARGET_BACK_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_TARGET_BACK_END_Y   (PIC_BUTTON_TARGET_BACK_START_Y + PIC_BUTTON_HEIGTH)

/*按键源坐标宏*/
/*原图序号*/
// 纵列：1启动，2返回，3设置，4信息
// 横行：1白色，2灰色，3红色，4黄色，5绿色
#define ICON_SOURCE_POWER_NUM   0
#define ICON_SOURCE_BACK_NUM    1
#define ICON_SOURCE_CONFIG_NUM  2
#define ICON_SOURCE_INFO_NUM    3

#define ICON_SOURCE_COLOR_WHITE_NUM     0
#define ICON_SOURCE_COLOR_GRAY_NUM      1
#define ICON_SOURCE_COLOR_RED_NUM       2
#define ICON_SOURCE_COLOR_YELLOW_NUM    3
#define ICON_SOURCE_COLOR_GREEN_NUM     4

#define PIC_BUTTON_WIDTH 65 //图标宽度
#define PIC_BUTTON_HEIGTH 65 //图标高度
#define PIC_BUTTON_SOURCE_INTERVAL_WIDTH 80 //源图片里图标间隔宽度
#define PIC_BUTTON_SOURCE_INTERVAL_HEIGTH 80 //源图片里图标间隔高度

#define PIC_BUTTON_SOURCE_INFO_START_X 5
#define PIC_BUTTON_SOURCE_INFO_START_Y (5 + PIC_BUTTON_SOURCE_INTERVAL_HEIGTH * ICON_SOURCE_INFO_NUM)
#define PIC_BUTTON_SOURCE_INFO_END_X   (PIC_BUTTON_SOURCE_INFO_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_SOURCE_INFO_END_Y   (PIC_BUTTON_SOURCE_INFO_START_Y + PIC_BUTTON_HEIGTH)

#define PIC_BUTTON_SOURCE_CONFIG_START_X 5
#define PIC_BUTTON_SOURCE_CONFIG_START_Y (5 + PIC_BUTTON_SOURCE_INTERVAL_HEIGTH * ICON_SOURCE_CONFIG_NUM)
#define PIC_BUTTON_SOURCE_CONFIG_END_X   (PIC_BUTTON_SOURCE_CONFIG_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_SOURCE_CONFIG_END_Y   (PIC_BUTTON_SOURCE_CONFIG_START_Y + PIC_BUTTON_HEIGTH)

#define PIC_BUTTON_SOURCE_POWER_START_X 5
#define PIC_BUTTON_SOURCE_POWER_START_Y (5 + PIC_BUTTON_SOURCE_INTERVAL_HEIGTH * ICON_SOURCE_POWER_NUM)
#define PIC_BUTTON_SOURCE_POWER_END_X   (PIC_BUTTON_SOURCE_POWER_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_SOURCE_POWER_END_Y   (PIC_BUTTON_SOURCE_POWER_START_Y + PIC_BUTTON_HEIGTH)

#define PIC_BUTTON_SOURCE_BACK_START_X 5
#define PIC_BUTTON_SOURCE_BACK_START_Y (5 + PIC_BUTTON_SOURCE_INTERVAL_HEIGTH * ICON_SOURCE_BACK_NUM)
#define PIC_BUTTON_SOURCE_BACK_END_X   (PIC_BUTTON_SOURCE_BACK_START_X + PIC_BUTTON_WIDTH)
#define PIC_BUTTON_SOURCE_BACK_END_Y   (PIC_BUTTON_SOURCE_BACK_START_Y + PIC_BUTTON_HEIGTH)


/**** MT感应数据结构体 ****/
struct ez_mt{
    int init; //初始化标志
    int display; //刷新标志
    int sync; //同步信号
    int sync_flag; //同步标志
    int id;  //触摸编号
    int state;  //触摸状态
    int state_index;//触摸状态阶段
    unsigned int x;      //触摸的X
    unsigned int y;      //触摸的Y


    unsigned int coord_flag[PARAMETER_MAXCOUNT]; //触摸按键标志
    unsigned int coord_id[PARAMETER_MAXCOUNT]; //触摸按键编号
    unsigned int coord_x[PARAMETER_MAXCOUNT]; //触摸按键位置x
    unsigned int coord_y[PARAMETER_MAXCOUNT]; //触摸按键位置y

    unsigned int coord_old_x[PARAMETER_MAXCOUNT]; //上一次触摸按键位置x
    // unsigned int iconold_x[PARAMETER_COUNT]; //触摸按键上次位置x
    // unsigned int iconold_y[PARAMETER_COUNT]; //触摸按键上次位置y

};

#define BUTTON_MAX 4 //0:起停（1）;1:信息（1）;2:返回（2）;
#define STATE_MAX 3 //0:待机;1:事件1;2:事件2;
/**** UI标志位结构体 ****/
struct ez_ui{
    char pic_path[64];
    int demo_id;    //界面模板ID
    int refresh;    //界面切换的刷新标志,1置位，0复位
    int page_index_cur;//当前页面位置
    int page_index_last;//上一页面位置
    int button_state[BUTTON_MAX][STATE_MAX]; //按键编号，按键状态

};

/**** HMI功能结构体 ****/
struct ez_hmi{
    int data_send;       //数据发送开关
    int power_flag;     //启动开关
    int impluses_lock_flag;      //脉冲按键锁开关
    int init_flag;      //初始化开关
    int warning_flag;   //报警标志,位检测。
    int error_flag;     //错误标志,位检测。

    struct ez_mt mt;
    struct ez_ui ui;

    float percent[PARAMETER_MAXCOUNT]; //百分比
    unsigned int value[PARAMETER_MAXCOUNT]; //设置的参数数值保存
};

void display_mt_coordtoval(struct ez_hmi *hmi);
void display_mt_valtocoord(struct ez_hmi *hmi);

void display_mt_init(struct ez_hmi *hmi);
void display_mt_read(int fd , struct ez_hmi *hmi);
void display_mt_handle(struct ez_hmi *hmi);
void display_mt_update_rt(struct ez_hmi *hmi);
void display_mt_update_sp(struct ez_hmi *hmi);

void display_ui_init(struct ez_hmi *hmi);

void hmi_send_to_system(struct ez_hmi *hmi);

extern struct ez_hmi ezhmi;

#endif /* __EZ_MT_DISPLAY_BSP_H */
